<?php

/**
 * @file
 * Module help file for consumer api
 */

use \Drupal\Core\Routing\RouteMatchInterface;
use \Drupal\Core\Url;

/**
 * Implements hook_help()
 */
 function consumer_api_test_help($route_name, RouteMatchInterface $route_match){
   switch($route_name){
     case 'help.page.consumer_api_test':
          $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('The Paragraphs Type permission module allows administrators to configure permissions individually for each <em>Paragraphs type</em>. For more information, see the <a href=":online">online documentation for the Paragraphs module</a>.', [':online' => 'https://www.drupal.org/node/2444881']) . '</p>';
      $output .= '<h3>' . t('Uses') . '</h3>';
      $output .= '<dt>' . t('Configuring permissions per Paragraphs type') . '</dt>';
      $output .= '<dd>' . t('Administrators can configure the permissions to view, create, edit, and delete each <em>Paragraphs type</em> individually on the <a href=":permissions">Permissions page</a>.', [':permissions' => Url::fromRoute('user.admin_permissions')->toString()]) . '</dd>';
      return $output;
   }
 }